export  const  CHANGE_HOT_SEARCHLIST="CHANGE_HOT_SEARCHLIST";
export  const  CHANGE_SEARCHLIST="CHANGE_SEARCHLIST";
export  const  CHANGE_HISTORY_LIST="CHANGE_HISTORY_LIST";
export  const  CHANGE_DELETE_HISTORY_LIST="CHANGE_DELETE_HISTORY_LIST";