export const CHANGE_SHOW_CATEGROYLIST = "CHANGE_SHOW_CATEGROYLIST";
export const CHANGE_SHOW_CATEGROYTYPELIST = "CHANGE_SHOW_CATEGROYTYPELIST";
export const CHANGE_SHOW_CATEGROYLISTMORE = "CHANGE_SHOW_CATEGROYLISTMORE";
export const CHANGE_SHOW_CITYLIST = "CHANGE_SHOW_CITYLIST";
export const CHANGE_SHOW_CITYLIID = "CHANGE_SHOW_CITYLIID";